# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LimberTabbarExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LimberTabbarExample
  pod 'LimberTabbar', :path => '../LimberTabbar'

end

# Workaround for Cocoapods issue #7689 (and #7606? - to be confirmed)
#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
#    config.build_settings.delete('CODE_SIGNING_REQUIRED')
#  end
#end
